services:
  app:
    build:
      context: ./src
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./src:/var/www
    depends_on:
      - db
    networks:
      - laravel
    links:
      - db
    environment:
      - TZ=UTC

  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel

  db:
    image: mysql:8.0
    container_name: laravel_mysql
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE: laravel
      - MYSQL_ROOT_PASSWORD: root_password
      - MYSQL_PASSWORD: user_password
      - MYSQL_USER: laravel_user
      - TZ: UTC
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - laravel

  scheduler:
    build:
      context: ./src
      dockerfile: Dockerfile
    container_name: laravel_scheduler
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./src:/var/www
    command:
      ["/bin/sh", "-c", "while sleep 60; do php artisan schedule:run; done"]
    depends_on:
      - db
    networks:
      - laravel
    links:
      - db
    environment:
      - TZ=UTC

networks:
  laravel:
    driver: bridge
